timokau/marvin-mk2

marvin/__main__.py
pre-commit.nix
setup.py

For https://github.com/nix-community/infra/issues/24.

Provide a command line entry point

---

marvin/__main__.py

Needed for https://github.com/nix-community/infra/pull/25/.

Optionally load secrets from file

---

marvin/__main__.py

Print the traceback and return HTTP 500 instead of crashing the entire
server.

Handle exceptions gracefully

---

marvin/__main__.py

Tested here: https://github.com/timokau/marvins-playground/issues/19

Disallow self reviews

---

marvin/__main__.py

Various improvements

---

marvin/__main__.py

Require explicit opt-in and allow it in any comment by the PR author.
See https://github.com/nix-community/infra/pull/26#issuecomment-643671446.

Explicit opt in

---

marvin/__main__.py

Used state at some places, status at others. Crucially the greeting
instructed users to use "state" while the command is "status".

Fix status terminology

---

marvin/__main__.py

Tested here: https://github.com/timokau/marvins-playground/pull/21#pullrequestreview-432769047

Respond to reviews

---

marvin/__main__.py

New changes invalidate reviews.
Tested here: https://github.com/timokau/marvins-playground/pull/21#issuecomment-645627488

Reset reviews on PR changes

---

marvin/__main__.py
marvin/team.py

Request reviews from a pool of volunteers while allowing them to disable requests at any time.
Fixes #2.
Tested here: https://github.com/timokau/marvins-playground/pull/21#issuecomment-646827038

Request reviews on need_merge

---

marvin/triage.py

Marvin assigned me to a bunch of merged PRs. Not intended behaviour.

Restrict triage to open PRs

---

marvin/team.py

As requested in
https://github.com/timokau/marvin-mk2/issues/34#issuecomment-653763687.
CC @fgaz

Add fgaz to the reviewer team

---

marvin/__main__.py
marvin/commands.py
marvin/status.py
tests/test_status.py

Review summaries may be empty. Threw an exception here: https://github.com/nixos/nixpkgs/pull/92197

Fix empty review summary crash

---

marvin/team.py

@glittershark @turion @symphorien

Add glittershark, turion and symphorien to the reviewer team

---

marvin/__main__.py
marvin/triage.py

Also use the review request fallback for reviewers

---

marvin/__main__.py
marvin/status.py
tests/test_status.py

Fixes #22 (kind of, as far as possible) and #75.

Automatic transitions

---

marvin/team.py

Stuff happening, lowering the limit for now

Lower fgaz's limit

---

marvin/gh_util.py
marvin/triage.py

Its easy to miss a notification in the email inbox. Fixes https://github.com/timokau/marvin-mk2/issues/69.

Post review and merge reminders before timeout

---

marvin/__main__.py
marvin/commands.py

Make it possible to opt-in in the PR description

---

marvin/team.py

I can't keep up with these reviews, sorry.

remove ryantm

---

marvin/team.py

Add kevincox

---

marvin/team.py

I didn't realize that this counted all GitHub activity. I was way over the previous values but understanding how it works makes me comfortable to commit more 🙂

Up kevincox's limit.

---

CONTRIBUTING.md
README.md

There wasn't really any central place to read up on marvin. Now there
is.

Rewrite the readme

---

marvin/team.py

I've already used marvin to get more attention to my PRs so now I want to try to give a little bit back. :100:

team: add bennyandresen (d=4, l=2)

---

marvin/team.py

https://github.com/timokau/marvin-mk2/issues/34#issuecomment-722376248

Add kisik21 to the reviewer team

---

.github/workflows/test.yml
marvin/team.py

https://github.com/timokau/marvin-mk2/issues/34#issuecomment-732306385

Add Ekleog to the reviewer team

---

marvin/team.py

https://github.com/timokau/marvin-mk2/issues/34#issuecomment-751397472
Welcome to the team @lovesegfault!

Add lovesegfault to the reviewer team

---

marvin/team.py

Welcome to the team @thiagokokada :tada: 
https://github.com/timokau/marvin-mk2/issues/34#issuecomment-754140193

Add thiagokokada to the reviewer team

---

marvin/team.py

black wants to add a line break because my username is to long?

Add supersandro2000 to the reviewer team

---

marvin/team.py

team.py: add asymmetric as reviewer

---

marvin/team.py

As requested. Thanks @kisik21!

Remove the reviewer entry for kisik21
